Backend/compiler/compiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
   url(r'^admin/', admin.site.urls),
   url(r'^problem/', include('problem.urls')),
]

Backend/compiler/problem/urls.py
from django.conf.urls import url
from problem import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register_user, name='register'),
    url(r'^logout/$', views.loguserout, name = 'loguserout'),
    url(r'^login/$', views.loguserin, name = 'loguserin'),
    url(r'^add-problem/$', views.add_problem, name = "add_problem"),
    url(r'^problems/$', views.all_problems, name = "all_problems"),
    url(r'^problems/(?P<pid>[\w\-]+)$', views.view_problem, name="view_prob"),
    url(r'^submit/(?P<pid>[\w\-]+)$', views.submit, name="submit"),
    url(r'^submission/(?P<submission_id>[\d]+)$', views.view_submission, name="view_sub"),

]

Backend/compiler/problem/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.forms import IntegerField

def in_upload_path(instance, filename):
    return "/".join(["testcases", str(instance.problem.id)]) + ".in"

def out_upload_path(instance, filename):
    return "/".join(["testcases", str(instance.problem.id)]) + ".out"
# Create your models here.

class Coder(models.Model):
    user = models.CharField(max_length=100)
    link = models.URLField()
    score = models.DecimalField(default=0, decimal_places= 3, max_digits= 100)
    rank = models.IntegerField(default = -1)
    problems_tried = models.IntegerField(null=True, default=0)
    problems_ac = models.IntegerField( null = False, default=0)

    def __unicode__(self):
        return self.user.username

class Problem(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=20, unique=True)
    link = models.URLField()
    statement = models.TextField()

    num_submission = models.IntegerField()
    num_ac = models.IntegerField(default=0)
    num_wa = models.IntegerField(default=0)
    num_re = models.IntegerField(default=0)
    num_tle = models.IntegerField(default=0)
    num_ce = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add= True)
    time_limit = models.IntegerField(default=1)
    source = models.CharField(max_length=200)
    num_tests = models.IntegerField(default=1)
    author =  models.CharField(max_length=50, default="admin")

    def __unicode__(self):
        return self.code
    

class TestCase(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    input_file = models.FileField(upload_to=in_upload_path)
    output_file = models.FileField(upload_to=out_upload_path)

    def __unicode__(self):
        return self.problem.code
LANGUAGES =(
    ("C", "GNU C"),
    ("CPP", "GNU C++"),
    )

   
class Submission(models.Model):
    STATUSES = (
        ("NT", "Not tested"),
        ("CE", "Compile Error"),
        ("TL", "Time Limit Exceed"),
        ("RE", "Runtime Error"),
        ("AC", "Accepted")
    )
    
    submitter = models.ForeignKey(Coder, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    status = models.CharField(max_length=2, default="NT", choices= STATUSES)
    lang = models.CharField(max_length= 4, default= "C", choices= LANGUAGES)
    code = models.TextField(default="")
    created = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=True)

Backend/compiler/problem/forms.py
from django import forms
from problem.models import Coder, Problem, TestCase, Submission
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = {'username', 'password'}

class ProblemForm(forms.ModelForm):
    name = forms.CharField()
    code = forms.CharField()
    statement = forms.CharField(widget = forms.Textarea)
    time_limit = forms.IntegerField()
    source = forms.CharField()
    input1 = forms.FileField()
    output1 = forms.FileField()

    class Meta:
        model = Problem
        fields = ['name', 'code', 'statement', 'time_limit', 'source', 'input1', 'output1']


class SubmissionForm(forms.ModelForm):
    langs = [("C", "C"),  ("CPP", "C++"), ("JAVA", "Java"), ("PYTH", "python"), ("PYTH3", "python 3")]
    lang = forms.ChoiceField(choices = langs)
    code = forms.CharField(widget = forms.Textarea)

    class Meta:
        model = Submission
        fields = ['lang', 'code']

Backend/compiler/problem/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from problem.models import Problem, Submission, Coder, TestCase
from problem.forms import UserForm, ProblemForm, SubmissionForm



def index(request):
    return render(request, "problem/index.html")


def register_user(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            # save the user to the db
            u = user_form.save()
            u.set_password(u.password)
            u.save()

            coder = Coder(user = u)
            coder.link = "/problem/users/%s" % (u.username)
            coder.score = 0
            # calculation of rank in the beginning
            coder.rank = -1
            for k in Coder.objects.all():
                coder.rank = max(coder.rank, k.rank)
            coder.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, "problem/register.html", {"user_form": user_form, "registered": registered})


def loguserin(request):
    # if form has been filled and sent by the user
    if request.method == 'POST':
        # get the username and password
        username = request.POST.get('username')
        password = request.POST.get('password')
        # authenticate the user using django's in built authenticate function
        user = authenticate(username=username, password=password)
        if user: # if the user exists log her in and redirect back to home page
            login(request, user)
            return HttpResponseRedirect('/problem/')
        else: # otherwise redirect to a page showing an error
            print("Invalid login details: {}, {}".format(username, password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request, "problem/login.html", {})


def loguserout(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect("/problem/")


def add_problem(request):
    # if user is not logged in, throw him to a sign-in page
    if not request.user.is_authenticated:
        return HttpResponseRedirect("/problem/login/")
    else:
        if request.method == 'POST':
            problem_form = ProblemForm(request.POST, request.FILES)
            if problem_form.is_valid():
                # save a new problem
                problem = problem_form.save()
                problem.save()
                return redirect("/problem/")
            else:
                problem_form = ProblemForm()
                return render(request, "problem/addproblem.html", {"problem_form": problem_form})

def view_problem(request, pid):
    problem = get_object_or_404(Problem, code = pid)
    payload = {"problem":problem}
    return render(request, "problem/problem.html", payload)

def all_problems(request):
    problems = Problem.objects.all()
    return render(request, "problem/all.html", {"problems":problems})

def submit(request, pid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/problem/login/')
    else:
        if request.method == 'POST':
            sub_form = SubmissionForm(request.POST)
            if sub_form.is_valid():
                sub = sub_form.save()
                sub.problem = Problem.objects.get(code = pid)
                print(sub.problem.code)
                sub.submitter = Coder.objects.get(user = request.user)
                print(sub.submitter)
                sub.save()
                return HttpResponseRedirect('/problem/submission/{}'.format(sub.id))
        else:
            sub_form = SubmissionForm()
            payload = {"sub_form":sub_form, "pid":pid}
            return render(request, "problem/submit.html", payload)

def view_submission(request, submission_id):
    required_sub = get_object_or_404(Submission, id = int(submission_id))
    if not required_sub.private or (required_sub.private and required_sub.submitter.user.username == request.user.username):
        return render(request, "problem/submission.html", {"submission": required_sub})
    else:
        return HttpResponseRedirect('/problem/')

Backend/compiler/problem/templates/problem/addproblem.html
{% extends 'problem/base.html' %}

{% block title %} Add a problem {% endblock %}

{% block body_block %}

    <h1> Add a problem </h1>
    <form id="add_problem_form" method="post" action="/problem/add-problem/"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ problem_form.as_p }}

        <input type="submit" name="submit" value = "add problem" />
    </form>
{% endblock %}

Backend/compiler/problem/templates/problem/all.html
{% extends 'problem/base.html' %}

{% block body_block %}
<div class="ui middle aligned animated list" style="position: relative;top: 100px; right: 700px">
    {% for p in problems %}
      <div class="item">
        <i class="rocket icon large" ></i>
        <div class="content">
          <div class="header">
          <p style="font-size: 50px">
              {{p.id}}. <a href="{{p.link}}">{{p.name}}</a>
          </p> 
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
{% endblock %}

Backend/compiler/problem/templates/problem/base.html
<!DOCTYPE html>
{%load static%}

<html lang="en">
    <head>
      <title> OJ </title>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"
      integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ=="
      crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
      integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
      crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
      integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
    </head>
<body>
  
  <header class="site-header">
    <nav class="navbar navbar-expand-sm py-1 navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
              </li>
          </div>
            <div class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-item nav-link" href="/problem/problems">Problems</a>
              </li>
            </div>

            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-item nav-link" href="'/problem/status'">Status</a>
              </li>
            </ul>
            {%if user.is_authenticated%}
            <div class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-item nav-link" href="/problem/add-problem">Add Problem</a>
              </li>
            </div>
            {%endif%}
            {%block submit%} {%endblock%}


            <div class="right menu">
    
              {%if user.is_authenticated%}
              <a href='/problem/logout'class="ui item">
                Logout
              </a>
              {% else %}
              <a href='/problem/login' class="ui item">
                Login 
              </a>
              {% endif %}
           
            </div>
        </div>
<div class="ui internally grid">
  <div class="row">
    <div class="three wide column">
      <img>
    </div>
    <div class="ten wide column">
   
        <div>
            {% block body_block %} {% endblock %}
        </div>

       

    </div>
    <div class="three wide column">
      <img>
    </div>
  </div>
  <div class="row">
    <div class="three wide column">
      <img>
    </div>
    <div class="ten wide column" style="position: relative;top: 300px">
   
    </div>
    <div class="three wide column">
      <img>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</header>


 </body>


</html>

Backend/compiler/problem/templates/problem/index.html
{% extends 'problem/base.html' %}

{% block body_block %}
<div style="position: relative;top: 150px;right: 500px">
    <p style="font-size: 72px"> NOOB CODERS </p>
</div>
{% endblock %}

Backend/compiler/problem/templates/problem/login.html
{% extends 'problem/base.html' %}

{% block title %} Login {% endblock %}
{% block body_block %}


<div style = "position: relative;left : 30px;">
    <div class="ui two column middle aligned very relaxed stackable grid" >
        <div class="column">
          <div class="ui form">
          <form id = "login_form" method = "post" action = "/problem/login/">
            {% csrf_token %}
            <div class="field">
              <label>Username</label>
              <div class="ui left icon input">
                <input placeholder="Username" type="text" name="username">
                <i class="user icon"></i>
              </div></div>
            <div class="field">
              <label>Password</label>
              <div class="ui left icon input">
                <input type="password" name="password" >
                <i class="lock icon"></i>
              </div>
            </div>
            <input type="submit" class="ui blue submit button" value="Login" >
                 </form>
                </div>
               
        </div>
       
      
        <div class="ui vertical divider">
          Or
        </div>
        <div class="center aligned column">
          <button onclick="window.location.href='/problem/register'" class="ui big green labeled icon button">
            <i class="signup icon"></i>
            Sign Up
          </button>
        </div>
      
      </div>
      
      {% endblock %}

Backend/compiler/problem/templates/problem/problem.html
{% extends 'problem/base.html' %}

{% block body_block %}
<div style="position: absolute;top: 100px">
<div>
    <h1> {{ problem.name}} </h1>
    <br/><br/>
    {{ problem.statement }}
 </div>
</div>
{% endblock %}

{% block submit %}
	<a class = "item" href="/problem/submit/{{problem.code}}/{{problem.statement}}">
		Submit
	</a>
{%endblock%}

Backend/compiler/problem/templates/problem/register.html
{% extends 'problem/base.html' %}

{% block title %} Register {%endblock%}
{% block body_block %}
<div style="position: relative;top: 400px;right: 450px">
    <h1> Register with NOOBS </h1>

        {% if registered %}
            Thank you for registering!
        {% else %}
        <form id="coder_form" method="post" action="/problem/register/"
                enctype = "multipart/form-data">
 {% csrf_token %}
<h4> Username </h4>
<div class="ui icon input">
    <div class="field">
  <input id="id_username" maxlength="30" name="username" type="text" />
  </div>
</div>



<h5>Password</h5>

<div class="ui  icon input">
    <div class="field">
      <input id="id_password" name="password" type="password" />
    </div>
    </div>
    <div style="position: relative;top: 20px; left: 40px">
       <input type="submit" name="submit" value="register with NOOBS" class="ui blue submit button" />

    </div>
</form>
    </div>        
        {% endif %}
{% endblock %}

Backend/compiler/problem/templates/problem/submission.html
{% extends "problem/base.html" %}

{% block body_block %}

	{{submission.submitter.user.username}}
	<br/>
	{{submission.status}}
	<br/>
	{{submission.lang}}
	<br/>
	{{submission.code}}
	<br/>

{% endblock %}

Backend/compiler/problem/templates/problem/submit.html
{% extends 'problem/base.html' %}

{% block body_block %}
<div style="position: relative;top: 50px">

    <h1> Submit a Solution!</h1>

   <form id="submit_form" method = "post" action = "/problem/submit/{{pid}}" class="ui fluid form" 
        enctype = "multipart/form-data">
        {% csrf_token %}
        <p><label class="ui right pointing label basic blue">Language:</label>
        <select id="id_lang" name="lang" class="ui dropdown" >
			<option value="C">C</option>
			<option value="CPP">C++</option>
		</select></p>
<p><label for="id_code">Code:</label> <textarea cols="40" id="id_code" name="code" rows="10">
</textarea></p>
<div style="position: relative;">
        <input type = "submit" name = "submit" value = "Submit"  class="ui button teal">
</div>    
    </form>

<script type="text/javascript">
	$('#id_lang')
	  .dropdown();
</script>
{% endblock %}